### ISSUE TITLE
How to train the re-ranker model?

### ISSUE THREAD

**Issue by ithieund** [Ravoxsg/SummaReranker#4]
Dear Mr. @Ravoxsg ,
In the readme, you only provide the pre-trained model checkpoints to reproduce the paper result. I couldn't find the section about how to train the re-ranker model to get that checkpoints. Could you please show me how to train the re-ranker model and save the pre-trained checkpoint file for next evaluation?

Thank you so much!

**Comment by Ravoxsg** [comment]
Hi @ithieund ,
I will release code for training soon (ETA ~ few weeks). 
So far I have released code for preparing the data + run the model with the 3 checkpoints I have shared.

**Comment by ithieund** [comment]
> Hi @ithieund , I will release code for training soon (ETA ~ few weeks). So far I have released code for preparing the data + run the model with the 3 checkpoints I have shared.

Thank you. I'll wait for that.

**Comment by ithieund** [comment]
> Hi @ithieund , I will release code for training soon (ETA ~ few weeks). So far I have released code for preparing the data + run the model with the 3 checkpoints I have shared.

Dear Mr. @Ravoxsg ,
It's about a month now so can you please release the training script next week?
Thank you so much!

**Comment by Ravoxsg** [comment]
Hi @ithieund 

I was busy with EMNLP deadline. 
I released the training pipeline! Please check it out.

**Comment by Ravoxsg** [comment]
By default everything is trained on Reddit-TIFU

**Comment by ithieund** [comment]
> Hi @ithieund
> 
> I was busy with EMNLP deadline. I released the training pipeline! Please check it out.

Thank you so much, Mr. @Ravoxsg !
