### ISSUE TITLE
ERROR: Cannot install -r requirements.txt (line 11) and huggingface-hub==0.2.1 because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by ithieund** [Ravoxsg/SummaReranker#6]
Dear Mr. @Ravoxsg ,
I cloned your code to Colab and ran the command `!pip install -r requirements.txt`.
When installing datasets==1.13.3, it throws the error below

<img width="614" alt="image" src="https://user-images.githubusercontent.com/4217195/169722392-6713e9d3-8f42-422c-967a-81c56fa756a1.png">

Can you please check this issue?
Thank you.

**Comment by ithieund** [comment]
The same error when running in my local Macbook. I think this issue is not related to Colab.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/4217195/169923779-82aeddc0-c424-48cf-9f84-e6a69a7f9e7b.png">

**Comment by Hannibal046** [comment]
Comment out this works for me

**Comment by ithieund** [comment]
> Comment out this works for me

Hi @Hannibal046 , I tried but it just lead to another error
<img width="536" alt="image" src="https://user-images.githubusercontent.com/4217195/170802633-71707573-0202-4b4b-b972-bb78c0c081f0.png">

Mr. @Ravoxsg , can you please fix this issue first?
Thank you.

**Comment by Ravoxsg** [comment]
@ithieund  I updated the requirements.txt file, please use the new one!

**Comment by ithieund** [comment]
> @ithieund I updated the requirements.txt file, please use the new one!

Dear Mr. @Ravoxsg ,
I pulled the new source code and run `pip install -r requirements.txt` again. Now it pass the error above but throws new errors. Please see the attached screenshot.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/4217195/181866119-dfb42209-f8ee-4f74-8b31-4e789415a787.png">
