### ISSUE TITLE
About the generate model

### ISSUE THREAD

**Issue by bingfeiz** [Ravoxsg/SummaReranker#7]
First of all, thank you very much for your help. I admire your work very much. When I replicated your model, I found that the generative model for fine-tuning on the dataset was missing when generating the candidate set. However, you have only published the reranker model, would you mind sharing your fine-tuned generative model?

**Comment by Ravoxsg** [comment]
Hi @bingfeiz ,

On CNN/DM and XSum, I used the public HuggingFace checkpoints as PEGASUS base models:
https://huggingface.co/google/pegasus-cnn_dailymail
and:
https://huggingface.co/google/pegasus-xsum

I shared my model trained on my training split of Reddit, please see the Readme for the download link.
